name: agenda-service-api-conformance-test
on:
  push:
  pull_request:

jobs:
  api-compliance-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        registry-url: https://registry.npmjs.org/
    - name: Install portman
      run: npm install -g @apideck/portman && portman -l kodata/docs/openapi.yaml -o api/postman/agenda-service.postman.json
    - name: Build the stack
      run: docker compose -f tests/docker-compose.yaml up -d
    - name: Install newman and run tests
      run: npm install -g newman && newman run api/postman/agenda-service.postman.json --env-var "baseUrl=http://localhost:8080"
    - name: Shutdown the stack
      run: docker compose -f tests/docker-compose.yaml down
